services:
  postgres:
    image: postgres:15
    container_name: toolrent-postgres-prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - toolrent-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: toolrent-keycloak-prod
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASS}
      KC_HOSTNAME: ${DOMAIN_NAME}
    ports:
      - "8080:8080"
    volumes:
      - ${KEYCLOAK_REALM_PATH:-../Backend-ToolRent/keycloak-realm}:/opt/keycloak/data/import  
    networks:
      - toolrent-network
    restart: unless-stopped

  toolrent-backend-1:
    image: ${BACKEND_IMAGE_NAME:-bigbenj4/toolrent-backend}:latest  
    build:
      context: ../Backend-ToolRent
      dockerfile: Dockerfile 
    volumes:
      - ./uploads:/uploads    
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_UPLOAD_DIR: /uploads
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/ToolRent-realm/protocol/openid-connect/certs
      REDIRECT_URI: http://${DOMAIN_NAME}:5173*
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "8090"
    networks:
        - toolrent-network
    restart: unless-stopped


  toolrent-frontend-1:
    image: ${FRONTEND_IMAGE_NAME:-bigbenj4/toolrent-frontend}:latest
    build:
      context: ../Frontend-ToolRent
      dockerfile: Dockerfile
    networks:
      - toolrent-network
    ports:
      - "5173:5173"
    restart: unless-stopped


  nginx:
    image: nginx
    container_name: toolrent-nginx
    ports:
      - "80:80" # Frontend
    volumes:
      - ${NGINX_CONF_PATH:-../Backend-ToolRent/nginx.conf}:/etc/nginx/conf.d/default.conf    
    networks:
      - toolrent-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  toolrent-network:
    driver: bridge