server:
  port: 0


spring:
  application:
    name: inventory-service
  cloud:
    config:
      enabled: true
      uri: ${URL_CONFIG}
  datasource:
    url: ${URL_DB}/inventory
    username: ${USER_DB}
    password: ${PASS_DB}
  jpa:
    hibernate:
      ddl-auto: update




